### ISSUE TITLE
XSAA 

### ISSUE THREAD

**Issue by nobananasforyou** [xyx98/my-vapoursynth-script#6]
Hello!

I switched to the latest revision of havsfunc and it does not seem to support the functions called by XSAA. Can you please make an update?

Failed to evaluate the script:
Python exception: havsfunc.mt_expand_multi outdated. Use https://github.com/Irrational-Encoding-Wizardry/vs-masktools instead.

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate

File "D:/test - Copy.vpy", line 16, in 
src = XSAA(src, nsize=4, nns=4, qual=2, aamode=0, maskmode=1)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\xvs.py", line 1250, in XSAA
mask=haf.mt_expand_multi(mask, 'losange', planes=[0], sw=1, sh=1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\havsfunc.py", line 4314, in mt_expand_multi
raise vs.Error("havsfunc.mt_expand_multi outdated. Use https://github.com/Irrational-Encoding-Wizardry/vs-masktools instead.")
vapoursynth.Error: havsfunc.mt_expand_multi outdated. Use https://github.com/Irrational-Encoding-Wizardry/vs-masktools instead.

**Comment by xyx98** [comment]
Should fix now.
